version: '3.1'
services:
  zookeeper:
    image: strimzi/kafka:latest-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: strimzi/kafka:latest-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  db2:
    container_name: db2
    environment:
        LICENSE: accept
        DBNAME: testdb
        DB2INSTANCE: db2inst1
        BLU: false
        TO_CREATE_SAMPLEDB: false
        DB2INST1_PASSWORD: ${DB2INST1_PASSWORD:-db2inst1}
        HADR_ENABLED: false
    image: ibmcom/db2:11.5.0.0a
    ports:
        - 50000:50000
        - 55000:55000
    privileged: true
    volumes:
        - ./db2data:/database
networks:
  default:
    external:
      name: kafkanet