version: '3.1'
services:
  connect:
    image: ibmcase/cdc-connector
    container_name: cdc-connector
    build:
      context:
        ./cdc
    ports:
      - 8083:8083
      - 5006:5005
    environment:
      - DEBEZIUM_VERSION=1.3
      - BOOTSTRAP_SERVERS=light-es-kafka-bootstrap-eventstreams.gse-eda-2020-10-3-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud:443
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=src_connect_configs
      - OFFSET_STORAGE_TOPIC=src_connect_offsets
      - STATUS_STORAGE_TOPIC=src_connect_statuses
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
      - KAFKA_DEBUG=true
      - DEBUG_SUSPEND_FLAG=n
  maven:
    image: maven
    container_name: orderms
    volumes:
      - "../:/app"
      - "~/.m2:/root/.m2"
    hostname: orderms
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      QUARKUS_PROFILE: dev
      DBUSER: ${DBUSER}
      DBPWD: ${DBPWD}
      SSLJDBCURL: ${SSLJDBCURL}
    ports:
      - "8080:8080"
      - "5005:5005"
    working_dir: /app
    command: "./mvnw quarkus:dev"
  