kind: PersistentVolume
apiVersion: v1
metadata:
  name: db2orders-pv
spec:
  capacity:
    storage: 100Mi
  flexVolume:
    driver: ibm/ibmc-block
    fsType: ext4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ibmc-block-gold
  volumeMode: Filesystem

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2orders-pvc
spec:
  storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi