kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: db2orders
  labels:
    app: db2orders
spec:
  replicas: 1
  account:
    privileged: true
  selector:
    matchLabels:
      app: db2orders
  template:
    metadata:
      labels:
        app: db2orders
    spec:
      containers:
        - name: db2orders
          image: ibmcase/db2orders
          imagePullPolicy: Always
          env:
            - name: LICENSE
              value: accept
            - name: DBNAME
              value: TESTDB
            - name: DB2INSTANCE
              value: db2inst1
            - name: DB2INST1_PASSWORD
              value: db2inst1
            - name: HADR_ENABLED
              value: "false"
            - name: TO_CREATE_SAMPLEDB
              value: "true"
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 50000
              protocol: TCP
            - containerPort: 55000
              protocol: TCP
            - containerPort: 60006
              protocol: TCP
            - containerPort: 60007
              protocol: TCP
          volumeMounts:
            - name: db2data
              mountPath: /database
          securityContext:
            allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: false
  volumeClaimTemplates:
  - metadata:
      name: db2data
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "ibmc-file-gold-gid"
      resources:
        requests:
          storage: 20Gi
