apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: orders
  namespace: integration
spec:
  partitions: 3
  replicas: 3
  topicName: orders
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824